// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { syncStorage } from '@/lib/storage';

const SUPABASE_URL = "https://alxuaxrykccielfsmyye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFseHVheHJ5a2NjaWVsZnNteXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTE3MTgsImV4cCI6MjA3NDI4NzcxOH0.MdzZrJX_UGZaewOxt1W06bh2WnRXmvz0uemBCgVP-OM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: syncStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});